/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'folkol' at '10/8/16 9:30 PM' with Gradle 3.1
 *
 * @author folkol, @date 10/8/16 9:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
